import json

# Load original questions
with open('app/resources/questions.json', 'r', encoding='utf-8') as f:
    qdata = json.load(f)

all_loaded = qdata['questions']
# Keep only original questions (no variation key)
questions = [q for q in all_loaded if 'variation' not in q]

# Real new questions for each knowledge point
new_questions = [
    # === 1.1.1 基本概念 ===
    {"id":"q1_1_1_1_v1","knowledge_point":"1.1.1 基本概念","difficulty":"easy","type":"choice",
     "question":"以下关于操作系统的描述，错误的是（）。",
     "options":["A. 操作系统是系统软件","B. 操作系统管理计算机资源","C. 操作系统是应用软件的一种","D. 操作系统提供用户接口"],
     "answer":"C","explanation":"操作系统是系统软件，不是应用软件。它负责管理计算机的硬件和软件资源。","variation":1},
    {"id":"q1_1_1_1_v2","knowledge_point":"1.1.1 基本概念","difficulty":"easy","type":"choice",
     "question":"操作系统的核心目标是（）。",
     "options":["A. 提高程序运行速度","B. 方便用户使用并提高资源利用率","C. 编写应用程序","D. 设计硬件电路"],
     "answer":"B","explanation":"操作系统的核心目标是方便用户使用计算机系统，同时提高系统资源的利用率。","variation":2},
    {"id":"q1_1_1_2_v1","knowledge_point":"1.1.1 基本概念","difficulty":"easy","type":"choice",
     "question":"操作系统不能完成的功能是（）。",
     "options":["A. 管理内存","B. 管理进程","C. 编写C语言程序","D. 管理文件系统"],
     "answer":"C","explanation":"编写C语言程序是程序员的工作，操作系统负责管理资源而非编写程序。","variation":1},
    {"id":"q1_1_1_2_v2","knowledge_point":"1.1.1 基本概念","difficulty":"easy","type":"choice",
     "question":"操作系统在计算机系统中的地位是（）。",
     "options":["A. 最底层的硬件","B. 最外层的应用","C. 硬件与应用之间的系统软件","D. 网络通信设备"],
     "answer":"C","explanation":"操作系统位于硬件和应用软件之间，是最基本的系统软件。","variation":2},
    {"id":"q1_1_1_3_v1","knowledge_point":"1.1.1 基本概念","difficulty":"medium","type":"choice",
     "question":"操作系统管理的主要对象不包括（）。",
     "options":["A. CPU","B. 内存","C. 用户","D. 外部设备"],
     "answer":"C","explanation":"操作系统管理CPU、内存、外部设备等资源，但不管理用户本身。","variation":1},
    {"id":"q1_1_1_3_v2","knowledge_point":"1.1.1 基本概念","difficulty":"medium","type":"choice",
     "question":"下列关于操作系统的说法，正确的是（）。",
     "options":["A. 操作系统可以脱离硬件运行","B. 操作系统是计算机系统的核心软件","C. 操作系统只管理软件","D. 操作系统只管理硬件"],
     "answer":"B","explanation":"操作系统是计算机系统的核心软件，它既管理硬件也管理软件资源。","variation":2},
    {"id":"q1_1_1_4_v1","knowledge_point":"1.1.1 基本概念","difficulty":"hard","type":"choice",
     "question":"操作系统作为资源管理器，其管理的资源不包括（）。",
     "options":["A. 处理器时间","B. 存储空间","C. 用户的个人想法","D. I/O设备"],
     "answer":"C","explanation":"操作系统管理处理器时间、存储空间和I/O设备等计算机资源。","variation":1},
    {"id":"q1_1_1_4_v2","knowledge_point":"1.1.1 基本概念","difficulty":"hard","type":"choice",
     "question":"从资源管理的角度看，操作系统的基本功能不包括（）。",
     "options":["A. 处理机管理","B. 存储器管理","C. 数据库管理","D. 设备管理"],
     "answer":"C","explanation":"数据库管理是数据库管理系统的功能，不是操作系统的基本功能。","variation":2},
    {"id":"q1_1_1_5_v1","knowledge_point":"1.1.1 基本概念","difficulty":"medium","type":"choice",
     "question":"用户通过（）与操作系统进行交互。",
     "options":["A. 操作系统接口","B. 编译器","C. 汇编器","D. 链接器"],
     "answer":"A","explanation":"用户通过操作系统提供的接口（命令接口、程序接口、图形接口）与系统进行交互。","variation":1},
    {"id":"q1_1_1_5_v2","knowledge_point":"1.1.1 基本概念","difficulty":"medium","type":"choice",
     "question":"操作系统提供的系统调用接口主要用于（）。",
     "options":["A. 用户直接操作硬件","B. 应用程序请求操作系统服务","C. 编译源代码","D. 网络连接"],
     "answer":"B","explanation":"系统调用接口是应用程序请求操作系统服务的程序接口。","variation":2},
    # === 1.1.2 计算机系统的视图 ===
    {"id":"q1_1_2_1_v1","knowledge_point":"1.1.2 计算机系统的视图","difficulty":"easy","type":"choice",
     "question":"在计算机系统层次结构中，最靠近硬件的是（）。",
     "options":["A. 应用程序","B. 操作系统","C. 用户","D. 编译器"],
     "answer":"B","explanation":"在计算机系统层次结构中，操作系统直接运行在硬件之上。","variation":1},
    {"id":"q1_1_2_1_v2","knowledge_point":"1.1.2 计算机系统的视图","difficulty":"easy","type":"choice",
     "question":"计算机系统的层次结构从底层到高层依次为（）。",
     "options":["A. 用户-应用-OS-硬件","B. 硬件-OS-应用-用户","C. OS-硬件-应用-用户","D. 应用-用户-OS-硬件"],
     "answer":"B","explanation":"计算机系统从底层到高层依次为：硬件、操作系统、应用程序、用户。","variation":2},
    {"id":"q1_1_2_2_v1","knowledge_point":"1.1.2 计算机系统的视图","difficulty":"medium","type":"choice",
     "question":"操作系统向用户隐藏了（）的复杂性。",
     "options":["A. 应用程序设计","B. 硬件操作细节","C. 网络通信","D. 数据库查询"],
     "answer":"B","explanation":"操作系统通过抽象接口向用户隐藏了硬件操作的复杂性。","variation":1},
    {"id":"q1_1_2_2_v2","knowledge_point":"1.1.2 计算机系统的视图","difficulty":"medium","type":"choice",
     "question":"从用户角度看，操作系统是（）。",
     "options":["A. 一组硬件设备","B. 一台虚拟机","C. 一个编译器","D. 一个数据库"],
     "answer":"B","explanation":"从用户角度看，操作系统将复杂的硬件抽象为一台功能更强的虚拟机。","variation":2},
    # === 1.1.3 操作系统的基本功能 ===
    {"id":"q1_1_3_1_v1","knowledge_point":"1.1.3 操作系统的基本功能","difficulty":"easy","type":"choice",
     "question":"下列哪项属于操作系统的功能（）。",
     "options":["A. 文字处理","B. 进程调度","C. 网页浏览","D. 视频播放"],
     "answer":"B","explanation":"进程调度是操作系统的核心功能之一。","variation":1},
    {"id":"q1_1_3_1_v2","knowledge_point":"1.1.3 操作系统的基本功能","difficulty":"easy","type":"choice",
     "question":"操作系统对CPU的管理主要通过（）实现。",
     "options":["A. 进程调度","B. 文件读写","C. 内存分配","D. 磁盘格式化"],
     "answer":"A","explanation":"操作系统通过进程调度来管理CPU资源的分配和使用。","variation":2},
    {"id":"q1_1_3_2_v1","knowledge_point":"1.1.3 操作系统的基本功能","difficulty":"easy","type":"choice",
     "question":"操作系统中负责管理输入输出设备的是（）。",
     "options":["A. 处理器管理模块","B. 存储管理模块","C. 设备管理模块","D. 文件管理模块"],
     "answer":"C","explanation":"设备管理模块负责管理所有输入输出设备。","variation":1},
    {"id":"q1_1_3_2_v2","knowledge_point":"1.1.3 操作系统的基本功能","difficulty":"easy","type":"choice",
     "question":"以下不属于操作系统五大功能的是（）。",
     "options":["A. 处理机管理","B. 存储器管理","C. 网络管理","D. 文件管理"],
     "answer":"C","explanation":"操作系统的五大功能是处理机管理、存储器管理、设备管理、文件管理和用户接口。","variation":2},
    {"id":"q1_1_3_3_v1","knowledge_point":"1.1.3 操作系统的基本功能","difficulty":"medium","type":"choice",
     "question":"操作系统中负责管理目录结构和文件存取的是（）。",
     "options":["A. 进程管理","B. 内存管理","C. 文件管理","D. 设备管理"],
     "answer":"C","explanation":"文件管理负责管理目录结构、文件的创建、删除、读写和存取控制。","variation":1},
    {"id":"q1_1_3_3_v2","knowledge_point":"1.1.3 操作系统的基本功能","difficulty":"medium","type":"choice",
     "question":"操作系统中虚拟存储器的实现属于（）的功能。",
     "options":["A. 处理机管理","B. 存储器管理","C. 文件管理","D. 设备管理"],
     "answer":"B","explanation":"虚拟存储器是存储器管理的重要功能。","variation":2},
    {"id":"q1_1_3_4_v1","knowledge_point":"1.1.3 操作系统的基本功能","difficulty":"hard","type":"choice",
     "question":"操作系统中实现多道程序并发执行的关键是（）。",
     "options":["A. 文件管理","B. 进程管理","C. 设备管理","D. 用户接口"],
     "answer":"B","explanation":"进程管理是实现多道程序并发执行的关键。","variation":1},
    {"id":"q1_1_3_4_v2","knowledge_point":"1.1.3 操作系统的基本功能","difficulty":"hard","type":"choice",
     "question":"操作系统中负责解决资源竞争和死锁问题的是（）。",
     "options":["A. 文件管理","B. 进程管理","C. 设备管理","D. 存储管理"],
     "answer":"B","explanation":"进程管理负责处理进程间的资源竞争、同步和死锁问题。","variation":2},
    # === 1.2 操作系统的形成和发展 ===
    {"id":"q1_2_1_v1","knowledge_point":"1.2 操作系统的形成和发展","difficulty":"easy","type":"choice",
     "question":"在操作系统发展史上，效率最低的阶段是（）。",
     "options":["A. 手工操作阶段","B. 批处理阶段","C. 多道程序阶段","D. 分时系统阶段"],
     "answer":"A","explanation":"手工操作阶段需要人工干预每个步骤，CPU利用率极低。","variation":1},
    {"id":"q1_2_1_v2","knowledge_point":"1.2 操作系统的形成和发展","difficulty":"easy","type":"choice",
     "question":"简单批处理系统的主要缺点是（）。",
     "options":["A. 不能自动执行","B. 缺乏交互性","C. 不能管理内存","D. 不能管理文件"],
     "answer":"B","explanation":"简单批处理系统的主要缺点是缺乏交互性。","variation":2},
    {"id":"q1_2_2_v1","knowledge_point":"1.2 操作系统的形成和发展","difficulty":"medium","type":"choice",
     "question":"多道程序设计技术的核心思想是（）。",
     "options":["A. 一次只运行一个程序","B. 内存中同时存放多个程序并发执行","C. 程序顺序执行","D. 程序独占CPU"],
     "answer":"B","explanation":"多道程序设计的核心思想是在内存中同时存放多个程序，使它们并发执行。","variation":1},
    {"id":"q1_2_2_v2","knowledge_point":"1.2 操作系统的形成和发展","difficulty":"medium","type":"choice",
     "question":"分时操作系统的主要目标是（）。",
     "options":["A. 提高吞吐量","B. 提供交互性和响应时间","C. 减少内存占用","D. 简化程序设计"],
     "answer":"B","explanation":"分时操作系统的主要目标是提供良好的交互性和较短的响应时间。","variation":2},
    {"id":"q1_2_3_v1","knowledge_point":"1.2 操作系统的形成和发展","difficulty":"medium","type":"choice",
     "question":"实时操作系统的主要特点是（）。",
     "options":["A. 高吞吐量","B. 严格的响应时间要求","C. 多用户交互","D. 大内存容量"],
     "answer":"B","explanation":"实时操作系统的主要特点是对响应时间有严格要求。","variation":1},
    {"id":"q1_2_3_v2","knowledge_point":"1.2 操作系统的形成和发展","difficulty":"medium","type":"choice",
     "question":"以下属于实时操作系统应用场景的是（）。",
     "options":["A. 文字处理","B. 工业控制","C. 网页浏览","D. 游戏娱乐"],
     "answer":"B","explanation":"工业控制是实时操作系统的典型应用场景。","variation":2},
    # === 1.3 操作系统的分类 ===
    {"id":"q1_3_1_v1","knowledge_point":"1.3 操作系统的分类","difficulty":"easy","type":"choice",
     "question":"以下不属于操作系统类型的是（）。",
     "options":["A. 批处理操作系统","B. 分时操作系统","C. 编译操作系统","D. 实时操作系统"],
     "answer":"C","explanation":"编译操作系统不是操作系统的分类。","variation":1},
    {"id":"q1_3_1_v2","knowledge_point":"1.3 操作系统的分类","difficulty":"easy","type":"choice",
     "question":"Windows操作系统属于（）。",
     "options":["A. 批处理操作系统","B. 分时操作系统","C. 实时操作系统","D. 网络操作系统"],
     "answer":"B","explanation":"Windows是典型的分时操作系统。","variation":2},
    {"id":"q1_3_2_v1","knowledge_point":"1.3 操作系统的分类","difficulty":"medium","type":"choice",
     "question":"现代操作系统通常具有的特征不包括（）。",
     "options":["A. 并发性","B. 共享性","C. 虚拟性","D. 单一性"],
     "answer":"D","explanation":"现代操作系统具有并发性、共享性、虚拟性和异步性四大特征。","variation":1},
    {"id":"q1_3_2_v2","knowledge_point":"1.3 操作系统的分类","difficulty":"medium","type":"choice",
     "question":"操作系统的异步性是指（）。",
     "options":["A. 程序执行顺序固定","B. 进程以不可预知的速度推进","C. 资源分配均匀","D. 用户操作同步"],
     "answer":"B","explanation":"异步性是指进程以不可预知的速度向前推进。","variation":2},
    {"id":"q1_3_3_v1","knowledge_point":"1.3 操作系统的分类","difficulty":"medium","type":"choice",
     "question":"银行ATM机使用的操作系统类型通常是（）。",
     "options":["A. 批处理操作系统","B. 分时操作系统","C. 实时操作系统","D. 网络操作系统"],
     "answer":"C","explanation":"银行ATM机需要快速响应用户操作，通常使用实时操作系统。","variation":1},
    {"id":"q1_3_3_v2","knowledge_point":"1.3 操作系统的分类","difficulty":"medium","type":"choice",
     "question":"以下属于批处理操作系统特点的是（）。",
     "options":["A. 交互性强","B. 响应时间短","C. 吞吐量大","D. 实时性高"],
     "answer":"C","explanation":"批处理操作系统的主要特点是吞吐量大。","variation":2},
    # === 2.1.2 多道程序的并发执行 ===
    {"id":"q2_1_2_1_v1","knowledge_point":"2.1.2 多道程序的并发执行","difficulty":"easy","type":"choice",
     "question":"多道程序并发执行时，宏观上表现为（）。",
     "options":["A. 程序依次执行","B. 程序同时执行","C. 程序不执行","D. 程序随机执行"],
     "answer":"B","explanation":"多道程序并发执行时，宏观上多个程序同时向前推进。","variation":1},
    {"id":"q2_1_2_1_v2","knowledge_point":"2.1.2 多道程序的并发执行","difficulty":"easy","type":"choice",
     "question":"多道程序并发执行可以提高（）。",
     "options":["A. 程序正确性","B. 系统资源利用率","C. 程序可读性","D. 程序可维护性"],
     "answer":"B","explanation":"多道程序并发执行的主要目的是提高系统资源的利用率。","variation":2},
    {"id":"q2_1_2_2_v1","knowledge_point":"2.1.2 多道程序的并发执行","difficulty":"medium","type":"choice",
     "question":"并发执行的程序之间（）。",
     "options":["A. 完全独立","B. 可能存在制约关系","C. 必须同步","D. 必须互斥"],
     "answer":"B","explanation":"并发执行的程序之间可能存在资源共享等制约关系。","variation":1},
    {"id":"q2_1_2_2_v2","knowledge_point":"2.1.2 多道程序的并发执行","difficulty":"medium","type":"choice",
     "question":"多道程序环境下，程序执行的结果具有（）。",
     "options":["A. 可再现性","B. 不可再现性","C. 确定性","D. 唯一性"],
     "answer":"B","explanation":"由于并发执行的异步性，程序执行的结果可能具有不可再现性。","variation":2},
    # === 2.2.1 进程的概念 ===
    {"id":"q2_2_1_1_v1","knowledge_point":"2.2.1 进程的概念","difficulty":"easy","type":"choice",
     "question":"进程是（）。",
     "options":["A. 程序的静态描述","B. 程序的一次执行过程","C. 一段代码","D. 一个文件"],
     "answer":"B","explanation":"进程是程序的一次执行过程，是系统进行资源分配和调度的基本单位。","variation":1},
    {"id":"q2_2_1_1_v2","knowledge_point":"2.2.1 进程的概念","difficulty":"easy","type":"choice",
     "question":"进程与程序的根本区别在于（）。",
     "options":["A. 进程有生命周期，程序没有","B. 进程是静态的，程序是动态的","C. 进程占用内存，程序不占用","D. 进程有代码，程序没有"],
     "answer":"A","explanation":"进程是动态的，有创建、执行、撤销的生命周期；程序是静态的代码集合。","variation":2},
    {"id":"q2_2_1_2_v1","knowledge_point":"2.2.1 进程的概念","difficulty":"medium","type":"choice",
     "question":"进程的基本状态不包括（）。",
     "options":["A. 就绪态","B. 执行态","C. 阻塞态","D. 编译态"],
     "answer":"D","explanation":"进程的基本状态包括就绪态、执行态和阻塞态。","variation":1},
    {"id":"q2_2_1_2_v2","knowledge_point":"2.2.1 进程的概念","difficulty":"medium","type":"choice",
     "question":"一个进程从就绪态变为执行态的条件是（）。",
     "options":["A. 获得CPU","B. 等待I/O完成","C. 时间片用完","D. 被阻塞"],
     "answer":"A","explanation":"进程从就绪态变为执行态需要获得CPU的使用权。","variation":2},
    {"id":"q2_2_1_3_v1","knowledge_point":"2.2.1 进程的概念","difficulty":"medium","type":"choice",
     "question":"进程的并发性是指（）。",
     "options":["A. 多个进程同时执行","B. 进程可以暂停","C. 进程可以撤销","D. 进程可以创建"],
     "answer":"A","explanation":"进程的并发性是指多个进程在宏观上同时向前推进。","variation":1},
    {"id":"q2_2_1_3_v2","knowledge_point":"2.2.1 进程的概念","difficulty":"medium","type":"choice",
     "question":"以下关于进程的描述，错误的是（）。",
     "options":["A. 进程是动态的","B. 进程有生命周期","C. 进程是静态的代码","D. 进程可以并发执行"],
     "answer":"C","explanation":"进程是动态的执行过程，不是静态的代码。","variation":2},
    # === 2.2.2 进程的实体 ===
    {"id":"q2_2_2_1_v1","knowledge_point":"2.2.2 进程的实体","difficulty":"easy","type":"choice",
     "question":"进程控制块（PCB）的作用是（）。",
     "options":["A. 存储程序代码","B. 记录进程状态和控制信息","C. 管理文件系统","D. 分配内存空间"],
     "answer":"B","explanation":"PCB是操作系统管理进程的数据结构，记录进程的状态、优先级、寄存器值等控制信息。","variation":1},
    {"id":"q2_2_2_1_v2","knowledge_point":"2.2.2 进程的实体","difficulty":"easy","type":"choice",
     "question":"进程实体由（）组成。",
     "options":["A. 程序段、数据段、PCB","B. 代码、注释、文档","C. 输入、输出、处理","D. 源程序、目标程序"],
     "answer":"A","explanation":"进程实体由程序段、数据段和进程控制块（PCB）三部分组成。","variation":2},
    {"id":"q2_2_2_2_v1","knowledge_point":"2.2.2 进程的实体","difficulty":"medium","type":"choice",
     "question":"PCB中不包含的信息是（）。",
     "options":["A. 进程状态","B. 程序计数器","C. 源代码","D. 优先级"],
     "answer":"C","explanation":"PCB中不包含源代码，源代码存储在程序段中。","variation":1},
    {"id":"q2_2_2_2_v2","knowledge_point":"2.2.2 进程的实体","difficulty":"medium","type":"choice",
     "question":"操作系统通过（）来感知进程的存在。",
     "options":["A. 程序代码","B. PCB","C. 数据段","D. 用户输入"],
     "answer":"B","explanation":"操作系统通过PCB来感知和管理进程，PCB是进程存在的唯一标志。","variation":2},
    # === 2.2.3 进程状态和转换 ===
    {"id":"q2_2_3_1_v1","knowledge_point":"2.2.3 进程状态和转换","difficulty":"easy","type":"choice",
     "question":"进程从执行态变为就绪态的原因是（）。",
     "options":["A. 时间片用完","B. 等待I/O","C. 获得CPU","D. 进程创建"],
     "answer":"A","explanation":"进程时间片用完后，从执行态变为就绪态。","variation":1},
    {"id":"q2_2_3_1_v2","knowledge_point":"2.2.3 进程状态和转换","difficulty":"easy","type":"choice",
     "question":"进程从执行态变为阻塞态的原因是（）。",
     "options":["A. 时间片用完","B. 请求I/O操作","C. 获得CPU","D. 进程终止"],
     "answer":"B","explanation":"进程请求I/O操作时，从执行态变为阻塞态。","variation":2},
    {"id":"q2_2_3_2_v1","knowledge_point":"2.2.3 进程状态和转换","difficulty":"medium","type":"choice",
     "question":"进程从阻塞态变为就绪态的条件是（）。",
     "options":["A. 获得CPU","B. I/O操作完成","C. 时间片用完","D. 进程创建"],
     "answer":"B","explanation":"当进程等待的I/O操作完成后，进程从阻塞态变为就绪态。","variation":1},
    {"id":"q2_2_3_2_v2","knowledge_point":"2.2.3 进程状态和转换","difficulty":"medium","type":"choice",
     "question":"以下状态转换不可能发生的是（）。",
     "options":["A. 就绪→执行","B. 执行→就绪","C. 阻塞→执行","D. 执行→阻塞"],
     "answer":"C","explanation":"进程不能直接从阻塞态变为执行态，必须先变为就绪态。","variation":2},
    {"id":"q2_2_3_3_v1","knowledge_point":"2.2.3 进程状态和转换","difficulty":"medium","type":"choice",
     "question":"三态模型中，进程处于就绪态表示（）。",
     "options":["A. 正在使用CPU","B. 等待I/O完成","C. 已获得除CPU外的所有资源","D. 已终止"],
     "answer":"C","explanation":"就绪态表示进程已获得除CPU外的所有必要资源。","variation":1},
    {"id":"q2_2_3_3_v2","knowledge_point":"2.2.3 进程状态和转换","difficulty":"medium","type":"choice",
     "question":"进程状态转换中，由操作系统主动引起的是（）。",
     "options":["A. 就绪→执行","B. 执行→阻塞","C. 阻塞→就绪","D. 执行→就绪"],
     "answer":"D","explanation":"执行→就绪（时间片用完）是由操作系统调度程序主动引起的。","variation":2},
    # === 2.2.4 进程控制 ===
    {"id":"q2_2_4_1_v1","knowledge_point":"2.2.4 进程控制","difficulty":"easy","type":"choice",
     "question":"创建新进程的系统调用通常是（）。",
     "options":["A. fork()","B. exit()","C. wait()","D. kill()"],
     "answer":"A","explanation":"fork()系统调用用于创建新进程。","variation":1},
    {"id":"q2_2_4_1_v2","knowledge_point":"2.2.4 进程控制","difficulty":"easy","type":"choice",
     "question":"进程终止时，操作系统需要（）。",
     "options":["A. 分配内存","B. 回收资源","C. 创建PCB","D. 启动I/O"],
     "answer":"B","explanation":"进程终止时，操作系统需要回收该进程占用的所有资源。","variation":2},
    {"id":"q2_2_4_2_v1","knowledge_point":"2.2.4 进程控制","difficulty":"medium","type":"choice",
     "question":"进程阻塞原语的作用是（）。",
     "options":["A. 创建新进程","B. 将进程从执行态变为阻塞态","C. 唤醒进程","D. 终止进程"],
     "answer":"B","explanation":"进程阻塞原语用于将当前执行的进程从执行态变为阻塞态。","variation":1},
    {"id":"q2_2_4_2_v2","knowledge_point":"2.2.4 进程控制","difficulty":"medium","type":"choice",
     "question":"进程唤醒原语的作用是（）。",
     "options":["A. 创建新进程","B. 将进程从阻塞态变为就绪态","C. 阻塞进程","D. 终止进程"],
     "answer":"B","explanation":"进程唤醒原语用于将等待的进程从阻塞态变为就绪态。","variation":2},
    # === 2.3.1 线程的概念 ===
    {"id":"q2_3_1_1_v1","knowledge_point":"2.3.1 线程的概念","difficulty":"easy","type":"choice",
     "question":"线程是（）。",
     "options":["A. 比进程更小的执行单位","B. 比进程更大的执行单位","C. 一种文件","D. 一种设备"],
     "answer":"A","explanation":"线程是比进程更小的执行单位，是CPU调度的基本单位。","variation":1},
    {"id":"q2_3_1_1_v2","knowledge_point":"2.3.1 线程的概念","difficulty":"easy","type":"choice",
     "question":"引入线程的主要目的是（）。",
     "options":["A. 减少内存占用","B. 提高并发度和系统响应速度","C. 简化程序设计","D. 增加安全性"],
     "answer":"B","explanation":"引入线程的主要目的是提高系统的并发度和响应速度。","variation":2},
    {"id":"q2_3_1_2_v1","knowledge_point":"2.3.1 线程的概念","difficulty":"medium","type":"choice",
     "question":"一个进程可以包含（）线程。",
     "options":["A. 只能一个","B. 最多两个","C. 多个","D. 不能包含"],
     "answer":"C","explanation":"一个进程可以包含多个线程，这些线程共享进程的资源。","variation":1},
    {"id":"q2_3_1_2_v2","knowledge_point":"2.3.1 线程的概念","difficulty":"medium","type":"choice",
     "question":"线程共享进程的资源不包括（）。",
     "options":["A. 代码段","B. 数据段","C. 打开的文件","D. 寄存器值"],
     "answer":"D","explanation":"线程共享进程的代码段、数据段和打开的文件等资源，但每个线程有自己独立的寄存器和栈。","variation":2},
    # === 2.3.2 线程与进程的比较 ===
    {"id":"q2_3_2_1_v1","knowledge_point":"2.3.2 线程与进程的比较","difficulty":"easy","type":"choice",
     "question":"进程和线程的主要区别是（）。",
     "options":["A. 进程是资源分配单位，线程是调度单位","B. 线程是资源分配单位，进程是调度单位","C. 两者完全相同","D. 线程比进程大"],
     "answer":"A","explanation":"进程是资源分配的基本单位，线程是CPU调度的基本单位。","variation":1},
    {"id":"q2_3_2_1_v2","knowledge_point":"2.3.2 线程与进程的比较","difficulty":"easy","type":"choice",
     "question":"线程切换的开销比进程切换（）。",
     "options":["A. 大","B. 小","C. 相同","D. 无法比较"],
     "answer":"B","explanation":"线程切换只需要保存和恢复少量寄存器，开销比进程切换小得多。","variation":2},
    {"id":"q2_3_2_2_v1","knowledge_point":"2.3.2 线程与进程的比较","difficulty":"medium","type":"choice",
     "question":"多线程程序中，一个线程崩溃会导致（）。",
     "options":["A. 整个进程崩溃","B. 只有该线程受影响","C. 系统重启","D. 其他进程崩溃"],
     "answer":"A","explanation":"在多线程程序中，一个线程崩溃通常会导致整个进程崩溃。","variation":1},
    {"id":"q2_3_2_2_v2","knowledge_point":"2.3.2 线程与进程的比较","difficulty":"medium","type":"choice",
     "question":"以下关于线程的描述，正确的是（）。",
     "options":["A. 线程有独立的地址空间","B. 线程共享所属进程的地址空间","C. 线程不能并发执行","D. 线程比进程创建开销大"],
     "answer":"B","explanation":"线程共享所属进程的地址空间。","variation":2},
    # === 2.3.3 线程的实现 ===
    {"id":"q2_3_3_1_v1","knowledge_point":"2.3.3 线程的实现","difficulty":"easy","type":"choice",
     "question":"用户级线程的调度由（）完成。",
     "options":["A. 操作系统内核","B. 用户级线程库","C. 硬件","D. 编译器"],
     "answer":"B","explanation":"用户级线程的调度由用户级线程库完成。","variation":1},
    {"id":"q2_3_3_1_v2","knowledge_point":"2.3.3 线程的实现","difficulty":"easy","type":"choice",
     "question":"内核级线程的优点是（）。",
     "options":["A. 切换开销小","B. 可以利用多处理器","C. 实现简单","D. 不需要操作系统支持"],
     "answer":"B","explanation":"内核级线程由操作系统内核管理，可以利用多处理器实现真正的并行执行。","variation":2},
    {"id":"q2_3_3_2_v1","knowledge_point":"2.3.3 线程的实现","difficulty":"medium","type":"choice",
     "question":"混合式线程实现结合了（）的优点。",
     "options":["A. 用户级和内核级线程","B. 进程和线程","C. 批处理和分时","D. 同步和异步"],
     "answer":"A","explanation":"混合式线程实现结合了用户级线程和内核级线程的优点。","variation":1},
    {"id":"q2_3_3_2_v2","knowledge_point":"2.3.3 线程的实现","difficulty":"medium","type":"choice",
     "question":"用户级线程的缺点是（）。",
     "options":["A. 不能利用多处理器","B. 切换开销大","C. 实现复杂","D. 需要内核支持"],
     "answer":"A","explanation":"用户级线程的主要缺点是不能利用多处理器。","variation":2},
    # === 3.1.2 临界资源与临界区 ===
    {"id":"q3_1_2_1_v1","knowledge_point":"3.1.2 临界资源与临界区","difficulty":"easy","type":"choice",
     "question":"临界资源是指（）。",
     "options":["A. 可以被多个进程同时访问的资源","B. 一次只允许一个进程访问的资源","C. 不重要的资源","D. 虚拟资源"],
     "answer":"B","explanation":"临界资源是指一次只允许一个进程访问的资源。","variation":1},
    {"id":"q3_1_2_1_v2","knowledge_point":"3.1.2 临界资源与临界区","difficulty":"easy","type":"choice",
     "question":"以下属于临界资源的是（）。",
     "options":["A. CPU寄存器","B. 打印机","C. 私有变量","D. 局部变量"],
     "answer":"B","explanation":"打印机是典型的临界资源，一次只能被一个进程使用。","variation":2},
    {"id":"q3_1_2_2_v1","knowledge_point":"3.1.2 临界资源与临界区","difficulty":"medium","type":"choice",
     "question":"临界区是指（）。",
     "options":["A. 访问临界资源的代码段","B. 进程的整个代码","C. 操作系统内核","D. 用户程序"],
     "answer":"A","explanation":"临界区是指进程中访问临界资源的那段代码。","variation":1},
    {"id":"q3_1_2_2_v2","knowledge_point":"3.1.2 临界资源与临界区","difficulty":"medium","type":"choice",
     "question":"进程进入临界区需要满足的条件是（）。",
     "options":["A. 任意进入","B. 互斥进入","C. 同时进入","D. 不需要条件"],
     "answer":"B","explanation":"进程进入临界区需要满足互斥条件。","variation":2},
    # === 3.1.4 信号量和P、V操作 ===
    {"id":"q3_1_4_1_v1","knowledge_point":"3.1.4 信号量和P、V操作","difficulty":"easy","type":"choice",
     "question":"信号量是一种（）。",
     "options":["A. 硬件设备","B. 整型变量","C. 程序","D. 文件"],
     "answer":"B","explanation":"信号量是一种特殊的整型变量，用于进程间的同步和互斥。","variation":1},
    {"id":"q3_1_4_1_v2","knowledge_point":"3.1.4 信号量和P、V操作","difficulty":"easy","type":"choice",
     "question":"P操作的作用是（）。",
     "options":["A. 增加信号量值","B. 减少信号量值","C. 初始化信号量","D. 删除信号量"],
     "answer":"B","explanation":"P操作（wait操作）将信号量值减1。","variation":2},
    {"id":"q3_1_4_2_v1","knowledge_point":"3.1.4 信号量和P、V操作","difficulty":"medium","type":"choice",
     "question":"V操作的作用是（）。",
     "options":["A. 减少信号量值","B. 增加信号量值并唤醒等待进程","C. 初始化信号量","D. 删除信号量"],
     "answer":"B","explanation":"V操作（signal操作）将信号量值加1，如果有进程在等待则唤醒一个。","variation":1},
    {"id":"q3_1_4_2_v2","knowledge_point":"3.1.4 信号量和P、V操作","difficulty":"medium","type":"choice",
     "question":"互斥信号量的初值通常设为（）。",
     "options":["A. 0","B. 1","C. -1","D. 任意值"],
     "answer":"B","explanation":"互斥信号量的初值通常设为1，表示临界资源初始时可用。","variation":2},
    {"id":"q3_1_4_3_v1","knowledge_point":"3.1.4 信号量和P、V操作","difficulty":"medium","type":"choice",
     "question":"信号量值为负数时表示（）。",
     "options":["A. 资源充足","B. 有进程在等待","C. 信号量无效","D. 系统错误"],
     "answer":"B","explanation":"信号量值为负数时，其绝对值表示等待该资源的进程数。","variation":1},
    {"id":"q3_1_4_3_v2","knowledge_point":"3.1.4 信号量和P、V操作","difficulty":"medium","type":"choice",
     "question":"P、V操作必须是（）。",
     "options":["A. 可中断的","B. 原子操作","C. 异步的","D. 并行的"],
     "answer":"B","explanation":"P、V操作必须是原子操作，即执行过程中不能被中断。","variation":2},
    # === 3.2.2 用P、V操作实现同步 ===
    {"id":"q3_2_2_1_v1","knowledge_point":"3.2.2 用P、V操作实现同步","difficulty":"easy","type":"choice",
     "question":"用信号量实现进程同步时，同步信号量的初值通常为（）。",
     "options":["A. 0","B. 1","C. -1","D. 资源数量"],
     "answer":"A","explanation":"同步信号量的初值通常为0。","variation":1},
    {"id":"q3_2_2_1_v2","knowledge_point":"3.2.2 用P、V操作实现同步","difficulty":"easy","type":"choice",
     "question":"进程同步是指（）。",
     "options":["A. 进程同时执行","B. 进程按一定顺序执行","C. 进程互斥执行","D. 进程随机执行"],
     "answer":"B","explanation":"进程同步是指多个进程按照一定的先后顺序执行。","variation":2},
    {"id":"q3_2_2_2_v1","knowledge_point":"3.2.2 用P、V操作实现同步","difficulty":"medium","type":"choice",
     "question":"生产者-消费者问题中，empty信号量表示（）。",
     "options":["A. 缓冲区中空闲位置数","B. 缓冲区中产品数","C. 互斥信号量","D. 进程数量"],
     "answer":"A","explanation":"empty信号量表示缓冲区中的空闲位置数。","variation":1},
    {"id":"q3_2_2_2_v2","knowledge_point":"3.2.2 用P、V操作实现同步","difficulty":"medium","type":"choice",
     "question":"生产者-消费者问题中，full信号量表示（）。",
     "options":["A. 缓冲区中空闲位置数","B. 缓冲区中产品数","C. 互斥信号量","D. 进程数量"],
     "answer":"B","explanation":"full信号量表示缓冲区中的产品数。","variation":2},
    # === 3.4.2 死锁的必要条件 ===
    {"id":"q3_4_2_1_v1","knowledge_point":"3.4.2 死锁的必要条件","difficulty":"easy","type":"choice",
     "question":"产生死锁的四个必要条件中，不包括（）。",
     "options":["A. 互斥条件","B. 请求和保持条件","C. 可剥夺条件","D. 环路等待条件"],
     "answer":"C","explanation":"死锁的四个必要条件是互斥、请求和保持、不可剥夺和环路等待。","variation":1},
    {"id":"q3_4_2_1_v2","knowledge_point":"3.4.2 死锁的必要条件","difficulty":"easy","type":"choice",
     "question":"死锁产生的互斥条件是指（）。",
     "options":["A. 资源可以共享","B. 资源一次只能被一个进程使用","C. 资源可以抢占","D. 资源数量充足"],
     "answer":"B","explanation":"互斥条件是指资源一次只能被一个进程使用。","variation":2},
    {"id":"q3_4_2_2_v1","knowledge_point":"3.4.2 死锁的必要条件","difficulty":"medium","type":"choice",
     "question":"死锁产生的请求和保持条件是指（）。",
     "options":["A. 进程请求新资源时保持已分配的资源","B. 进程释放所有资源","C. 进程不请求资源","D. 资源可以共享"],
     "answer":"A","explanation":"请求和保持条件是指进程已经保持了至少一个资源，但又请求新的资源而被阻塞。","variation":1},
    {"id":"q3_4_2_2_v2","knowledge_point":"3.4.2 死锁的必要条件","difficulty":"medium","type":"choice",
     "question":"死锁产生的环路等待条件是指（）。",
     "options":["A. 进程形成等待环路","B. 进程顺序执行","C. 资源充足","D. 没有等待"],
     "answer":"A","explanation":"环路等待条件是指存在一个进程等待环路。","variation":2},
    # === 3.4.4 死锁的避免 ===
    {"id":"q3_4_4_1_v1","knowledge_point":"3.4.4 死锁的避免","difficulty":"easy","type":"choice",
     "question":"银行家算法用于（）。",
     "options":["A. 死锁预防","B. 死锁避免","C. 死锁检测","D. 死锁恢复"],
     "answer":"B","explanation":"银行家算法是一种死锁避免算法。","variation":1},
    {"id":"q3_4_4_1_v2","knowledge_point":"3.4.4 死锁的避免","difficulty":"easy","type":"choice",
     "question":"死锁避免与死锁预防的区别是（）。",
     "options":["A. 避免更严格","B. 预防更严格","C. 两者相同","D. 避免不需要检查"],
     "answer":"B","explanation":"死锁预防通过破坏死锁的必要条件来防止死锁，条件更严格。","variation":2},
    {"id":"q3_4_4_2_v1","knowledge_point":"3.4.4 死锁的避免","difficulty":"medium","type":"choice",
     "question":"银行家算法中，安全状态是指（）。",
     "options":["A. 系统不会发生死锁","B. 系统已经死锁","C. 资源充足","D. 没有进程"],
     "answer":"A","explanation":"安全状态是指系统能够按照某种顺序为每个进程分配资源，使所有进程都能完成。","variation":1},
    {"id":"q3_4_4_2_v2","knowledge_point":"3.4.4 死锁的避免","difficulty":"medium","type":"choice",
     "question":"银行家算法的核心思想是（）。",
     "options":["A. 随意分配资源","B. 在分配前检查系统是否安全","C. 不分配资源","D. 只分配给第一个进程"],
     "answer":"B","explanation":"银行家算法的核心思想是在每次资源分配前进行安全性检查。","variation":2},
    # === 3.5.1 读者-写者问题 ===
    {"id":"q3_5_1_1_v1","knowledge_point":"3.5.1 读者-写者问题","difficulty":"easy","type":"choice",
     "question":"读者-写者问题中，读者之间（）。",
     "options":["A. 必须互斥","B. 可以并发读","C. 不能同时读","D. 必须同步"],
     "answer":"B","explanation":"读者-写者问题中，多个读者可以同时读共享数据。","variation":1},
    {"id":"q3_5_1_1_v2","knowledge_point":"3.5.1 读者-写者问题","difficulty":"easy","type":"choice",
     "question":"读者-写者问题中，写者与写者之间（）。",
     "options":["A. 可以并发写","B. 必须互斥","C. 可以同时写","D. 不需要互斥"],
     "answer":"B","explanation":"写者与写者之间必须互斥。","variation":2},
    {"id":"q3_5_1_2_v1","knowledge_point":"3.5.1 读者-写者问题","difficulty":"medium","type":"choice",
     "question":"读者优先策略是指（）。",
     "options":["A. 写者优先执行","B. 只要有读者在读，新读者可以直接读","C. 读者和写者交替执行","D. 写者不能执行"],
     "answer":"B","explanation":"读者优先策略是指只要有读者在读，新来的读者可以直接读。","variation":1},
    {"id":"q3_5_1_2_v2","knowledge_point":"3.5.1 读者-写者问题","difficulty":"medium","type":"choice",
     "question":"写者优先策略是指（）。",
     "options":["A. 读者优先执行","B. 有写者等待时，新读者需要等待","C. 读者和写者同时执行","D. 写者不能执行"],
     "answer":"B","explanation":"写者优先策略是指当有写者等待时，新来的读者需要等待。","variation":2},
    # === 3.5.2 哲学家进餐问题 ===
    {"id":"q3_5_2_1_v1","knowledge_point":"3.5.2 哲学家进餐问题","difficulty":"easy","type":"choice",
     "question":"哲学家进餐问题中，哲学家的数量是（）。",
     "options":["A. 3个","B. 4个","C. 5个","D. 6个"],
     "answer":"C","explanation":"经典的哲学家进餐问题中有5个哲学家。","variation":1},
    {"id":"q3_5_2_1_v2","knowledge_point":"3.5.2 哲学家进餐问题","difficulty":"easy","type":"choice",
     "question":"哲学家进餐问题中，筷子的数量是（）。",
     "options":["A. 3根","B. 4根","C. 5根","D. 6根"],
     "answer":"C","explanation":"5个哲学家围坐，每两人之间放一根筷子，共5根筷子。","variation":2},
    {"id":"q3_5_2_2_v1","knowledge_point":"3.5.2 哲学家进餐问题","difficulty":"medium","type":"choice",
     "question":"解决哲学家进餐问题的方法之一是（）。",
     "options":["A. 增加筷子数量","B. 限制同时进餐的人数","C. 让哲学家不吃饭","D. 移除桌子"],
     "answer":"B","explanation":"限制同时进餐的人数（最多4人）可以避免死锁。","variation":1},
    {"id":"q3_5_2_2_v2","knowledge_point":"3.5.2 哲学家进餐问题","difficulty":"medium","type":"choice",
     "question":"哲学家进餐问题中，奇数号哲学家先拿左边筷子的策略是为了（）。",
     "options":["A. 增加死锁概率","B. 破坏环路等待条件","C. 减少筷子数量","D. 提高进餐速度"],
     "answer":"B","explanation":"奇数号先拿左筷、偶数号先拿右筷，可以破坏环路等待条件。","variation":2},
]

# Build all questions list
all_questions = list(questions)
for nq in new_questions:
    all_questions.append(nq)

all_questions.sort(key=lambda q: q['id'])

qdata['questions'] = all_questions
with open('app/resources/questions.json', 'w', encoding='utf-8') as f:
    json.dump(qdata, f, ensure_ascii=False, indent=2)

print(f"Total questions: {len(all_questions)}")
print(f"Original: {len(questions)}")
print(f"New variations: {len(new_questions)}")
