
let TAB="overview",DATA={};const app=document.getElementById('app');const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pct=v=>Math.round((Number(v)||0)*100)+'%';function bar(v){return '<div class="bar"><span style="width:'+pct(v)+'"></span></div>'}
async function load(){try{DATA=await fetch('/teacher/tools/data').then(r=>r.json())}catch(e){DATA={success:false,error:e.message}}render()}
function render(){if(TAB==='overview')overview();else if(TAB==='students')students();else if(TAB==='profiles')profiles();else if(TAB==='resourceManage')resources();else if(TAB==='questionBank')questions();else if(TAB==='graph')graph()}
function overview(){let s=DATA.summary||{};app.innerHTML='<div class="grid"><div class="stat">学生人数<b>'+Number(s.student_count||0)+'</b><span class="muted">当前班级</span></div><div class="stat">平均掌握度<b>'+pct(s.avg_mastery)+'</b><span class="muted">基于知识点画像</span></div><div class="stat">薄弱学生<b>'+Number(s.weak_student_count||0)+'</b><span class="muted">掌握度低于70%</span></div><div class="stat">资源 / 题目<b>'+Number(s.resource_count||0)+' / '+Number(s.question_count||0)+'</b><span class="muted">课程材料规模</span></div></div><div class="card"><h2>重点关注学生</h2>'+studentTable((DATA.students||[]).slice(0,7),false)+'</div>'}
function studentTable(list,actions=true){return '<table class="table"><thead><tr><th>学号</th><th>姓名</th><th>等级</th><th>掌握度</th><th>正确率</th>'+(actions?'<th>操作</th>':'')+'</tr></thead><tbody>'+list.map(s=>'<tr><td>'+esc(s.num)+'</td><td><b>'+esc(s.name)+'</b></td><td><span class="tag">'+esc(s.level)+'</span></td><td>'+pct(s.avg_mastery)+bar(s.avg_mastery)+'</td><td>'+pct(s.accuracy)+'</td>'+(actions?'<td><a class="btn light" href="/teacher/students?sid='+encodeURIComponent(s.id)+'">详情</a></td>':'')+'</tr>').join('')+'</tbody></table>'}
function students(){app.innerHTML='<div class="card"><h2>学生管理</h2>'+studentTable(DATA.students||[],true)+'</div>'}
function profiles(){let sid=new URLSearchParams(location.search).get('sid');if(sid){profile(sid);return}app.innerHTML='<div class="card"><h2>学生画像列表</h2>'+studentTable(DATA.students||[],true)+'</div>'}
async function profile(sid){let d=await fetch('/teacher/student-profile/data?sid='+encodeURIComponent(sid)).then(r=>r.json());let p=d.profile||{},m=d.mastery||{},pts=m.points||[];app.innerHTML='<a class="btn light" href="/teacher/students">&lt; 返回学生画像列表</a><div class="card"><h2>学生画像</h2><div class="grid"><div class="stat">学习等级<b>'+esc(p.level||'暂无')+'</b></div><div class="stat">平均掌握度<b>'+pct(p.avg_mastery)+'</b></div><div class="stat">正确率<b>'+pct(p.accuracy)+'</b></div><div class="stat">做题总数<b>'+Number(p.total_questions||0)+'</b></div></div><p class="muted">'+esc(p.description||'')+'</p></div><div class="card"><h2>知识点学习明细</h2><table class="table"><thead><tr><th>知识点</th><th>综合掌握度</th><th>做题</th><th>视频</th><th>资源</th><th>讨论</th></tr></thead><tbody>'+pts.map(k=>'<tr><td><b>'+esc(k.name||k.full_name)+'</b></td><td>'+pct(k.score)+bar(k.score)+'</td><td>'+pct(k.exercise_score)+'</td><td>'+pct(k.video_score)+'</td><td>'+pct(k.resource_score)+'</td><td>'+pct(k.discussion_score)+'</td></tr>').join('')+'</tbody></table></div>'}
async function resources(){let d=await fetch('/teacher/resources/data').then(r=>r.json()),list=d.resources||[];app.innerHTML='<div class="card"><h2>资源管理</h2><table class="table"><thead><tr><th>文件名</th><th>类型</th><th>知识点</th><th>更新时间</th><th>大小</th></tr></thead><tbody>'+list.map(r=>'<tr><td><b>'+esc(r.name)+'</b></td><td>'+esc(r.type)+'</td><td>'+esc(r.knowledge_point||'未绑定')+'</td><td>'+esc(r.updated_at||'')+'</td><td>'+Math.round((r.size||0)/1024)+' KB</td></tr>').join('')+'</tbody></table></div>'}
async function questions(){let d=await fetch('/teacher/questions/data').then(r=>r.json()),list=d.questions||[];app.innerHTML='<div class="card"><h2>题库管理</h2><table class="table"><thead><tr><th>ID</th><th>知识点</th><th>难度</th><th>题目</th><th>答案</th></tr></thead><tbody>'+list.map(q=>'<tr><td>'+esc(q.id)+'</td><td>'+esc(q.knowledge_point)+'</td><td>'+esc({easy:'简单',medium:'中等',hard:'困难'}[q.difficulty]||q.difficulty)+'</td><td>'+esc(q.question)+'</td><td>'+esc(q.answer)+'</td></tr>').join('')+'</tbody></table></div>'}
function graph(){app.innerHTML='<div class="card"><h2>公共知识图谱关系</h2><p class="muted">公共图谱关系由 Neo4j 数据驱动；学生端会按课程、章、大节、知识点四级展示。</p></div>'}
load();
